exclusive_server_id: # BOTの専属サーバーのID
exclusive_server_name: # BOTの専属サーバーの名前
log_channel_id: # ログを吐き出すチャンネルのID
cooldown: # 同じメッセージを送信できる間隔
warning_role_id: # 警告ロールのID
timeout_duration: # タイムアウトする期間
max_allows_multi_post_channels_count: # マルチポストができるチャンネルの個数
